kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-redis-master
  namespace: guestbook
spec:
  storageClassName: redis
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
