apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: guestbook
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  # Two replicas additionally to the one master.
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        # Tell slaves to get hosts from dns. Alternatively
        # these can be set via environment variables.
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 6379