apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: frontend
        image: eu.gcr.io/loodse-training-playground/loodse-training/frontend:1.0.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080