apiVersion: kubeone.io/v1beta1
kind: KubeOneCluster
name: k1
versions:
  kubernetes: '1.21.5'
cloudProvider:
  gce: {}
  cloudConfig: |-
    [global]
    regional = true
# Addons are Kubernetes manifests to be deployed after provisioning the cluster
addons:
  enable: true
  # In case when the relative path is provided, the path is relative
  # to the KubeOne configuration file.
  path: "./addons"
