# Dex Is the OpenID Provider for Kubermatic.
dex:
  # configure your base domain, under which the Kubermatic dashboard shall be available
  ingress:
    host: "kubermatic.TODO-STUDENT-DNS.loodse.training"
  clients:
  # The "kubermatic" client is used for logging into the Kubermatic dashboard. It always needs to be configured.
  - id: kubermatic
    name: Kubermatic
    # generate a secure secret key with:
    # cat /dev/urandom | tr -dc A-Za-z0-9 | head -c32
    secret: "TODO-A-RANDOM-KEY"
    RedirectURIs:
    - https://kubermatic.TODO-STUDENT-DNS.loodse.training
    - https://kubermatic.TODO-STUDENT-DNS.loodse.training/projects
  # For testing purposes, we configure a single static user/password combination.
  staticPasswords:
    - email: "TODO-STUDENT-EMAIL@loodse.training"
      # bcrypt hash of the string "password", can be created using recent versions of htpasswd:
      # `htpasswd -bnBC 10 "" PASSWORD_HERE | tr -d ':\n' | sed 's/$2y/$2a/'`
      hash: "$2a$10$GIfuOhkTsbmdKISjFOFA6u88cr8BS0g3sZYp1kKJ3Fb/CUVryW1i2"
      # these are used within Kubermatic to identify the user
      username: "TODO-STUDENT-EMAIL@loodse.training"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

