apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kubermatic-backup
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"  
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
reclaimPolicy: Delete
parameters:
  type: pd-standard
