apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  completions: 10
  parallelism: 5
  template:
    spec:
      containers:
        - name: my-job
          image: busybox
          command: ["sleep"]
          args: ["10"]
      restartPolicy: Never
