apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: my-app
  labels:
    app: my-app
spec:
  containers:
    - name: my-app
      image: eu.gcr.io/ps-workspace/loodse-training/multistaged-builds:0.0.3
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: my-volume
          mountPath: /srv/app/config
  volumes:
    - name: my-volume
      configMap:
        name: my-configmap
