apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: alpine
      image: alpine:3.12.0
      volumeMounts:
        - name: my-volume
          mountPath: /app
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
          echo $(date) >> /app/buffer;
          sleep 5;
          done
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc