apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: prometheus
  labels:
    app: prometheus
data:
  prometheus.yml: |-

    global:
      scrape_interval: 10s
      scrape_timeout: 5s

    scrape_configs:
      - job_name: node-exporter
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            regex: (.*):(\d+)
            target_label: __address__
            replacement: ${1}:9100
      - job_name: kubelet
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            regex: (.*):(\d+)
            target_label: __address__
            replacement: ${1}:10255
      - job_name: cadvisor
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            regex: (.*):(\d+)
            target_label: __address__
            replacement: ${1}:10255/cadvisor            
      - job_name: kube-state-metrics
        static_configs:
          - targets:
            - kube-state-metrics:8080
            - kube-state-metrics:8081

      # - job_name: 'kubernetes-cadvisor'
      #   scheme: https
      #   tls_config:
      #     ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      #   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      #   kubernetes_sd_configs:
      #     - role: node
      #   relabel_configs:
      #     - action: labelmap
      #       regex: __meta_kubernetes_node_label_(.+)
      #     - target_label: __address__
      #       replacement: kubernetes.default.svc:443
      #     - source_labels: [__meta_kubernetes_node_name]
      #       regex: (.+)
      #       target_label: __metrics_path__
      #       replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor