apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  namespace: training
  name: backend
spec:
  host: "*"
  subsets:
    - name: v1
      labels:
        version: 1.0.0
  trafficPolicy:
    outlierDetection:
      consecutiveErrors: 3
      interval: 1m
      baseEjectionTime: 15m

    # TODO  https://www.youtube.com/watch?v=iiRjCL4oa5E