apiVersion: v1
kind: Pod
metadata:
  name: fire
spec:
  containers:
    - name: fire
      image: nginx:1.19.2
      resources:
        limits:
          cpu: 25m
        requests:
          cpu: 25m
