apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: training
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: backend
        image: eu.gcr.io/loodse-training-playground/kubernetes-servicemesh/backend:1.0.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080