apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: backend
        image: eu.gcr.io/loodse-training-playground/loodse-training/backend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080